language: cpp
os: linux
compiler: clang

addons:
	apt:
		packages:
			- libglfw3-dev
			- libglfw3
			- libeigen3-dev
			- libboost-all-dev
			- libglm-dev

before_script:
	- cmake .

script:
	- make
	- ./test
